### PR TITLE
Feat: IPSets

### PR DESCRIPTION
**Pull request by vboufleur**
This PR adds a centralized IPSets management feature. No more we'll have to be manually updating ipsets across multiple AWS accounts, it can be defined in code and replicated for use by WAF rules everywhere its needed. Check the examples for defining ipsets on `values/ipsets/*` and for using them in the WebACLs on `values/ip-sets.json`.

This PR also refactors `bin/aws-firewall-factory.ts`, by adding some comments for better organization and gathering duplicated code, like the outputting of the aws-firewall-factory banner, on a function.

I haven't bumped versions here because there is another [PR](https://github.com/globaldatanet/aws-firewall-factory/pull/78) of mine that is opened that already bumped versions. To avoid conflicts I've decided to wait for the merge.

Let me know if you think some changes are needed! I've enabled "Edits by maintainers", so feel free to change it if you want to.

Happy coding!

### CODE REVIEW

**Comment by vboufleur** [comment]
@daknhh as you've merged my previous PR that bumped versions, I've rebased this branch on top of master and also bumped versions. It's ready for your review and merge.

**Comment by daknhh** [comment]
@vboufleur  thanks for adjustment. I will check this the week after next week since, i have so much stuff todo currently and this needs little bit more time for review, so i hope you dont mind. Thanks for all your effort <3

**Comment by daknhh** [comment]
@vboufleur  thanks for adjustment. I will check this the week after next week since, i have so much stuff todo currently and this needs little bit more time for review, so i hope you dont mind. Thanks for all your effort <3

**Comment by daknhh** [comment]
@vboufleur just to let you know i am doing few adjustments of your code here: https://github.com/globaldatanet/aws-firewall-factory/tree/pullrequests/vboufleur/feat/centralized-ipsets - nothing big just few little things. Also testing right now.

**Comment by daknhh** [comment]
WAFInvalidParameterException: Error reason: The ARN isn't valid. A valid ARN begins with arn: and includes other information separated by colons or slashes., field: RESOURCE_ARN, parameter: -> not working

**Comment by vboufleur** [comment]
Hi @daknhh! I've seen your commits and couldn't quickly identify the issue. That error happened to me when aws-firewall-factory couldn't replace the reference for the ARN of the ipset (`${IPAllow.Arn}`) for the real value (`arn:aws:wafv2:...`).

Tomorrow I'll reserve some time for checking your code and see why that error happened.

Can you please pass to me the JSONs of the ipsets and of the config that deploys them so that I can reproduce this issue?

**Comment by daknhh** [comment]
Hi @vboufleur i think the problem is here:

```
      for (const rule of rules) {
        const ipSetARN = rule.Statement?.IPSetReferenceStatement?.ARN;
        if(!ipSetARN) continue;
        if(ipSetARN.startsWith("arn:aws:")) continue; // ARN was manually defined by the user, skip checking
        if(!ipSetARN.startsWith("${") || !ipSetARN.endsWith(".Arn}")) logErrorAndExit(`IPSetReferenceStatement.ARN must be indicating the name of the IPSet, accessing its ARN, which CloudFormation will substitute on deploying.\n  Detected value: '${ipSetARN}'.\n` +  "  Example of expected value: '${IPsString.Arn}'");

        const ipSetName = ipSetARN.split(".")[0].replace(/[${]/g, "");
        if(!ipSetsNames.includes(ipSetName)) logErrorAndExit(`IPSet named '${ipSetName}' not found on the names of the ipsets on the JSON files defined in the 'config.WebAcl.IPSetFiles' prop.\n  These were the ones which were defined: ${ipSetsNames.reduce((acc, curr) => acc === "" ? `'${curr}'` : `${acc} | '${curr}'`, "")}`);
      }
```
Here we need to recursively check for the  IPSetReferenceStatement because - a IPSetReferenceStatement can also part of and And Statement or an  Or Statement
Additionally, i think this is not needed:
```
      // Add Fn::Sub for replacing IPSets logical name with its real ARN after deployment
      // const subStatement = cloneDeep(statement.Statement);
      // if (subStatement.IPSetReferenceStatement && subStatement.IPSetReferenceStatement.ARN.startsWith("${")) {
      //   subStatement.IPSetReferenceStatement.ARN = cdk.Fn.sub(subStatement.IPSetReferenceStatement.ARN);
      // }
```
because i am already doing a fn sub for the whole managedServiceData here:

```
     managedServiceData: cdk.Fn.sub(
          JSON.stringify(managedServiceData)
        ),
```

Example Json for Firewall

```
{
  "General": {
    "Prefix": "test",
    "Stage": "dev",
    "S3LoggingBucketName": "",
    "DeployHash": "",
    "FireHoseKeyArn": "",
    "SecuredDomain": [
      "login-local.dev.test.de"
    ]
  },
  "WebAcl": {
    "Name": "idp",
    "Scope": "REGIONAL",
    "Type": "AWS::ElasticLoadBalancingV2::LoadBalancer",
    "IncludeMap": {
      "account": [
        ""
      ]
    },
    "IPSetFiles": [
      "keycloak-admin-ip-whitelist-test"
    ],
    "PreProcess": {{
      "Name": "KeycloakAdminIPWhitelist-login-local",
      "Statement": {
        "AndStatement": {
          "Statements": [
            {
              "IPSetReferenceStatement": {
                "ARN": "${IPsString}"
              }
            },
            {
              "ByteMatchStatement": {
                "FieldToMatch": {
                  "SingleHeader": {
                    "Name": "host"
                  }
                },
                "PositionalConstraint": "EXACTLY",
                "SearchString": "login-local.dev.test.de",
                "TextTransformations": [
                  {
                    "Type": "NONE",
                    "Priority": 0
                  }
                ]
              }
            }
          ]
        }
      },
      "Action": {
        "Allow": {}
      },
      "VisibilityConfig": {
        "SampledRequestsEnabled": true,
        "CloudWatchMetricsEnabled": true
      }
    },},
    "PostProcess": {
      "ManagedRuleGroups": [
        {
          "Vendor": "AWS",
          "Name": "AWSManagedRulesAmazonIpReputationList",
          "Capacity": 25,
          "Version": ""
        },
        {
          "Vendor": "AWS",
          "Name": "AWSManagedRulesCommonRuleSet",
          "Capacity": 700,
          "Version": "Version_1.6"
        }
      ]
    }
  }
}
```

**Comment by daknhh** [comment]
@vboufleur any news regarding the issue or should I take a look at it?

**Comment by vboufleur** [comment]
Hi @daknhh! I got too busy the past week, and I'm still busy in the current one. If you want to, you can take a look at the issue, or, this weekend I'll be free. I plan to spend some time taking a look at the branch and applying a fix. Please let me know if you'll wait for me or if you'll fix the issue yourself.

**Comment by daknhh** [comment]
@vboufleur no worries, i am also very busy these days. Feel free to check the issue. If you need help just let me know <3

**Comment by daknhh** [comment]
i think i fixed the stuff: https://github.com/globaldatanet/aws-firewall-factory/tree/pullrequests/vboufleur/feat/centralized-ipsets

**Comment by daknhh** [comment]
I will merge this PR the next days. https://github.com/globaldatanet/aws-firewall-factory/pull/131 -> Just make sure to test everything from a-z right now

**Pull request closed without merging**
